const SQL_REQUEST_Foreign_Keys = `SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = ? AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_SCHEMA = 'new_look'`;
const SQL_REQUEST_Foreign_Keys2 = `SELECT COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, TABLE_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = ? AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_SCHEMA = 'new_look';`;
const SQL_REQUEST_Tables_Ref = `SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_NAME = ? AND TABLE_SCHEMA = 'new_look';`



module.exports = {
    SQL_REQUEST_Foreign_Keys, SQL_REQUEST_Tables_Ref, SQL_REQUEST_Foreign_Keys2
};

